INSERT INTO authors (name, nationality) VALUES ('J.K. Rowling', 'British');
INSERT INTO authors (name, nationality) VALUES ('Stephen King', 'American');
INSERT INTO authors (name, nationality) VALUES ('Haruki Murakami', 'Japanese');
INSERT INTO authors (name, nationality) VALUES ('Neil Gaiman', 'British');
INSERT INTO authors (name, nationality) VALUES ('Agatha Christie', 'British');
INSERT INTO authors (name, nationality) VALUES ('H.P. Lovecraft', 'American');
INSERT INTO genres (name) VALUES ('Fantasy');
INSERT INTO genres (name) VALUES ('Horror');
INSERT INTO genres (name) VALUES ('Mystery');
INSERT INTO genres (name) VALUES ('Science Fiction');
INSERT INTO genres (name) VALUES ('Thriller');
INSERT INTO genres (name) VALUES ('Romance');
INSERT INTO books (title, author_id, isbn, price, stock, description, genre_id, publication_year) VALUES ('Harry Potter and the Sorcerer-s Stone', 1, '978-0590353427', 12.99, 100, 'The first book in the Harry Potter series', 1, 1997);
INSERT INTO books (title, author_id, isbn, price, stock, description, genre_id, publication_year) VALUES ('The Shining', 2, '978-0307743657', 10.50, 80, 'A horror novel by American author Stephen King', 2, 1977);
INSERT INTO books (title, author_id, isbn, price, stock, description, genre_id, publication_year) VALUES ('Norwegian Wood', 3, '978-0375704024', 14.25, 120, 'A novel by Japanese author Haruki Murakami', 3, 1987);
INSERT INTO books (title, author_id, isbn, price, stock, description, genre_id, publication_year) VALUES ('American Gods', 4, '978-0380789030', 11.99, 90, 'A fantasy novel by British author Neil Gaiman', 1, 2001);
INSERT INTO books (title, author_id, isbn, price, stock, description, genre_id, publication_year) VALUES ('Murder on the Orient Express', 5, '978-0062693662', 9.75, 110, 'A mystery novel by British author Agatha Christie', 3, 1934);
INSERT INTO books (title, author_id, isbn, price, stock, description, genre_id, publication_year) VALUES ('The Call of Cthulhu', 6, '978-0486287628', 8.99, 85, 'A horror short story by American author H.P. Lovecraft', 2, 1928);
INSERT INTO users (username, password, email, role) VALUES ('user', '$2a$10$BXrKwOhmV53H/4J8/.7Db.0VKW11LwOn6NqKvkq27HcNlKa39OEvq', 'user1@example.com', 'USER');
INSERT INTO users (username, password, email, role) VALUES ('admin', '$2a$10$fIgHcoZFeAMUhHH3s0XJIOHibgcrVoLx3t1J1N6soi8JDl.SeSd4C', 'admin@example.com', 'ADMIN');
INSERT INTO users (username, password, email, role) VALUES ('ana', '$2a$10$e3uZ5BWFtLSGRp8tGe6lI.L7x6RFOEDwsd2cNAbOasbZW7bPokqTi', 'user2@example.com', 'USER');
INSERT INTO carts (user_id) VALUES (1);
INSERT INTO carts (user_id) VALUES (3);